-- MySQL Script generated by MySQL Workbench
-- 10/08/15 18:48:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema diavgeiainsights
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `diavgeiainsights` ;

-- -----------------------------------------------------
-- Schema diavgeiainsights
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `diavgeiainsights` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `diavgeiainsights` ;

-- -----------------------------------------------------
-- Table `diavgeiainsights`.`decisions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diavgeiainsights`.`decisions` ;

CREATE TABLE IF NOT EXISTS `diavgeiainsights`.`decisions` (
  `ada` VARCHAR(15) NOT NULL COMMENT '',
  `protocolNumber` VARCHAR(45) NULL COMMENT '',
  `subject` VARCHAR(45) NULL COMMENT '',
  `issueDate` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL COMMENT '',
  `decisionTypeId` VARCHAR(45) NULL COMMENT '',
  `organizationId` VARCHAR(45) NULL COMMENT '',
  `privateData` VARCHAR(45) NULL COMMENT '',
  `submissionTimestamp` VARCHAR(45) NULL COMMENT '',
  `status` VARCHAR(45) NULL COMMENT '',
  `versionId` VARCHAR(45) NULL COMMENT '',
  `documentChecksum` VARCHAR(45) NULL COMMENT '',
  `correctedVersionId` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`ada`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diavgeiainsights`.`unitsperdecisions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diavgeiainsights`.`unitsperdecisions` ;

CREATE TABLE IF NOT EXISTS `diavgeiainsights`.`unitsperdecisions` (
  `upd_ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `upd_ada` VARCHAR(45) NULL COMMENT '',
  `unitID` INT NULL COMMENT '',
  PRIMARY KEY (`upd_ID`)  COMMENT '',
  INDEX `ADA_FK_idx` (`upd_ada` ASC)  COMMENT '',
  CONSTRAINT `UPD_ADA_FK`
    FOREIGN KEY (`upd_ada`)
    REFERENCES `diavgeiainsights`.`decisions` (`ada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diavgeiainsights`.`signersperdecisions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diavgeiainsights`.`signersperdecisions` ;

CREATE TABLE IF NOT EXISTS `diavgeiainsights`.`signersperdecisions` (
  `spd_ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `spd_ada` VARCHAR(15) NULL COMMENT '',
  `signerID` INT NULL COMMENT '',
  PRIMARY KEY (`spd_ID`)  COMMENT '',
  INDEX `ADA_FK_idx` (`spd_ada` ASC)  COMMENT '',
  CONSTRAINT `SPD_ADA_FK`
    FOREIGN KEY (`spd_ada`)
    REFERENCES `diavgeiainsights`.`decisions` (`ada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diavgeiainsights`.`amountWithKae`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diavgeiainsights`.`amountWithKae` ;

CREATE TABLE IF NOT EXISTS `diavgeiainsights`.`amountWithKae` (
  `awk_ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `awk_ada` VARCHAR(20) NULL COMMENT '',
  `afm` VARCHAR(30) NULL COMMENT '',
  `afmType` VARCHAR(45) NULL COMMENT '',
  `afmCountry` VARCHAR(45) NULL COMMENT '',
  `enterName` TINYINT(1) NULL COMMENT '',
  `name` VARCHAR(100) NULL COMMENT '',
  `noVATOrg` VARCHAR(45) NULL COMMENT '',
  `kae` VARCHAR(45) NOT NULL COMMENT '',
  `amount` FLOAT NOT NULL COMMENT '',
  `kaeCreditRemainder` FLOAT NULL COMMENT '',
  `kaeBudgetRemainder` FLOAT NULL COMMENT '',
  PRIMARY KEY (`awk_ID`)  COMMENT '',
  INDEX `ADA_FK_idx` (`awk_ada` ASC)  COMMENT '',
  CONSTRAINT `AWK_ADA_FK`
    FOREIGN KEY (`awk_ada`)
    REFERENCES `diavgeiainsights`.`decisions` (`ada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diavgeiainsights`.`decisionsB13`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diavgeiainsights`.`decisionsB13` ;

CREATE TABLE IF NOT EXISTS `diavgeiainsights`.`decisionsB13` (
  `b13_ada` VARCHAR(15) NOT NULL COMMENT '',
  `financialYear` TINYINT NOT NULL COMMENT '',
  `budgettype` VARCHAR(45) NOT NULL COMMENT '',
  `entryNumber` VARCHAR(20) NULL COMMENT '',
  `partialead` TINYINT(1) NOT NULL COMMENT '',
  `recalledExpenseDecision` TINYINT(1) NULL COMMENT '',
  `amount` FLOAT NULL COMMENT '',
  `currency` VARCHAR(45) NULL COMMENT '',
  `relatedPartialADA` VARCHAR(20) NULL COMMENT '',
  `documentType` VARCHAR(20) NULL COMMENT '',
  `amountWithKae_ID` INT NOT NULL COMMENT '',
  PRIMARY KEY (`b13_ada`)  COMMENT '',
  INDEX `fk_decisionsB13_amountWithKae1_idx` (`amountWithKae_ID` ASC)  COMMENT '',
  CONSTRAINT `fk_decisionsB13_amountWithKae1`
    FOREIGN KEY (`amountWithKae_ID`)
    REFERENCES `diavgeiainsights`.`amountWithKae` (`awk_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `B13_ADA_FK`
    FOREIGN KEY (`b13_ada`)
    REFERENCES `diavgeiainsights`.`decisions` (`ada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diavgeiainsights`.`decisionsB21`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diavgeiainsights`.`decisionsB21` ;

CREATE TABLE IF NOT EXISTS `diavgeiainsights`.`decisionsB21` (
  `b13_ada` VARCHAR(15) NOT NULL COMMENT '',
  `afm` VARCHAR(45) NULL COMMENT '',
  `afmType` VARCHAR(45) NULL COMMENT '',
  `afmCountry` VARCHAR(45) NULL COMMENT '',
  `enterName` TINYINT(1) NULL COMMENT '',
  `decisionsB21col` VARCHAR(45) NULL COMMENT '',
  `name` VARCHAR(100) NULL COMMENT '',
  `noVATOrg` VARCHAR(45) NULL COMMENT '',
  `documentType` VARCHAR(20) NULL COMMENT '',
  PRIMARY KEY (`b13_ada`)  COMMENT '',
  CONSTRAINT `B21_ADA_FK`
    FOREIGN KEY (`b13_ada`)
    REFERENCES `diavgeiainsights`.`decisions` (`ada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diavgeiainsights`.`decisionsB22`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diavgeiainsights`.`decisionsB22` ;

CREATE TABLE IF NOT EXISTS `diavgeiainsights`.`decisionsB22` (
  `b22_ada` VARCHAR(15) NOT NULL COMMENT '',
  `afm` VARCHAR(45) NULL COMMENT '',
  `afmType` VARCHAR(45) NULL COMMENT '',
  `afmCountry` VARCHAR(45) NULL COMMENT '',
  `enterName` TINYINT(1) NULL COMMENT '',
  `name` VARCHAR(100) NULL COMMENT '',
  `noVATOrg` VARCHAR(45) NULL COMMENT '',
  `documentType` VARCHAR(20) NULL COMMENT '',
  PRIMARY KEY (`b22_ada`)  COMMENT '',
  CONSTRAINT `B22_ADA_FK`
    FOREIGN KEY (`b22_ada`)
    REFERENCES `diavgeiainsights`.`decisions` (`ada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diavgeiainsights`.`sponsor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diavgeiainsights`.`sponsor` ;

CREATE TABLE IF NOT EXISTS `diavgeiainsights`.`sponsor` (
  `sp_ada` VARCHAR(15) NOT NULL COMMENT '',
  `afm` VARCHAR(45) NULL COMMENT '',
  `afmType` VARCHAR(45) NULL COMMENT '',
  `afmCountry` VARCHAR(45) NULL COMMENT '',
  `enterName` TINYINT(1) NULL COMMENT '',
  `name` VARCHAR(100) NULL COMMENT '',
  `noVATOrg` VARCHAR(45) NULL COMMENT '',
  `amount` VARCHAR(45) NULL COMMENT '',
  `currency` VARCHAR(45) NULL COMMENT '',
  `cpv` VARCHAR(15) NULL COMMENT '',
  `kae` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`sp_ada`)  COMMENT '',
  CONSTRAINT `SPO_ADA_FK`
    FOREIGN KEY (`sp_ada`)
    REFERENCES `diavgeiainsights`.`decisions` (`ada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diavgeiainsights`.`decisionsD1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diavgeiainsights`.`decisionsD1` ;

CREATE TABLE IF NOT EXISTS `diavgeiainsights`.`decisionsD1` (
  `d1_ada` VARCHAR(15) NOT NULL COMMENT '',
  `afm` VARCHAR(45) NULL COMMENT '',
  `afmType` VARCHAR(45) NULL COMMENT '',
  `afmCountry` VARCHAR(45) NULL COMMENT '',
  `enterName` TINYINT(1) NULL COMMENT '',
  `name` VARCHAR(100) NULL COMMENT '',
  `noVATOrg` VARCHAR(45) NULL COMMENT '',
  `amount` VARCHAR(45) NULL COMMENT '',
  `currency` VARCHAR(45) NULL COMMENT '',
  `assignmentType` VARCHAR(45) NULL COMMENT '',
  `textRelatedADA` VARCHAR(15) NULL COMMENT '',
  PRIMARY KEY (`d1_ada`)  COMMENT '',
  CONSTRAINT `D1_ADA_FK`
    FOREIGN KEY (`d1_ada`)
    REFERENCES `diavgeiainsights`.`decisions` (`ada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diavgeiainsights`.`cpvperdecisions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diavgeiainsights`.`cpvperdecisions` ;

CREATE TABLE IF NOT EXISTS `diavgeiainsights`.`cpvperdecisions` (
  `cpd_ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `cpd_ada` VARCHAR(15) NOT NULL COMMENT '',
  `cpv` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`cpd_ID`)  COMMENT '',
  INDEX `ADA_FK_idx` (`cpd_ada` ASC)  COMMENT '',
  CONSTRAINT `CPV_ADA_FK`
    FOREIGN KEY (`cpd_ada`)
    REFERENCES `diavgeiainsights`.`decisions` (`ada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diavgeiainsights`.`decisionsD21`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diavgeiainsights`.`decisionsD21` ;

CREATE TABLE IF NOT EXISTS `diavgeiainsights`.`decisionsD21` (
  `d21_ada` VARCHAR(15) NOT NULL COMMENT '',
  `contestProgressType` VARCHAR(45) NULL COMMENT '',
  `manifestSelectionCriterion` VARCHAR(45) NULL COMMENT '',
  `manifestContractType` VARCHAR(45) NULL COMMENT '',
  `orgBudgetCode` VARCHAR(45) NULL COMMENT '',
  `amount` FLOAT NULL COMMENT '',
  `currency` VARCHAR(45) NULL COMMENT '',
  `textRelatedADA` VARCHAR(45) NULL COMMENT '',
  `documentType` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`d21_ada`)  COMMENT '',
  CONSTRAINT `D21_ADA_FK`
    FOREIGN KEY (`d21_ada`)
    REFERENCES `diavgeiainsights`.`decisions` (`ada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diavgeiainsights`.`decisionsD22`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diavgeiainsights`.`decisionsD22` ;

CREATE TABLE IF NOT EXISTS `diavgeiainsights`.`decisionsD22` (
  `d22_ada` VARCHAR(15) NOT NULL COMMENT '',
  `afm` VARCHAR(20) NULL COMMENT '',
  `afmType` VARCHAR(45) NULL COMMENT '',
  `afmCountry` VARCHAR(45) NULL COMMENT '',
  `enterName` TINYINT(1) NULL COMMENT '',
  `name` VARCHAR(100) NULL COMMENT '',
  `noVATOrg` VARCHAR(45) NULL COMMENT '',
  `amount` FLOAT NULL COMMENT '',
  `currency` VARCHAR(45) NULL COMMENT '',
  `textRelatedADA` VARCHAR(100) NULL COMMENT '',
  `relatedDecisionsADA` VARCHAR(15) NULL COMMENT '',
  `decisionsD22col` VARCHAR(45) NULL COMMENT '',
  `documentType` VARCHAR(20) NULL COMMENT '',
  PRIMARY KEY (`d22_ada`)  COMMENT '',
  CONSTRAINT `D22_ADA_FK`
    FOREIGN KEY (`d22_ada`)
    REFERENCES `diavgeiainsights`.`decisions` (`ada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diavgeiainsights`.`preferences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diavgeiainsights`.`preferences` ;

CREATE TABLE IF NOT EXISTS `diavgeiainsights`.`preferences` (
  `pref_ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `pref_name` VARCHAR(45) NULL COMMENT '',
  `pref_value` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`pref_ID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diavgeiainsights`.`organisations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diavgeiainsights`.`organisations` ;

CREATE TABLE IF NOT EXISTS `diavgeiainsights`.`organisations` (
  `uid` INT NOT NULL COMMENT '',
  `label` VARCHAR(100) NULL COMMENT '',
  `abbreviation` VARCHAR(75) NULL COMMENT '',
  `latinName` VARCHAR(45) NULL COMMENT '',
  `category` VARCHAR(45) NULL COMMENT '',
  `organizationDomains` VARCHAR(45) NULL COMMENT '',
  `status` VARCHAR(45) NULL COMMENT '',
  `supervisorId` VARCHAR(45) NULL COMMENT '',
  `supervisorLabel` VARCHAR(45) NULL COMMENT '',
  `website` VARCHAR(65) NULL COMMENT '',
  `odeManagerEmail` VARCHAR(45) NULL COMMENT '',
  `vatNumber` VARCHAR(45) NULL COMMENT '',
  `fekNumber` VARCHAR(45) NULL COMMENT '',
  `fekIssue` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`uid`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
